# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIver1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Documents/PlatformIO/Projects/kelco_test_001/beta.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:0.957447, y2:1, stop:0 rgba(136, 138, 133, 255), stop:1 rgba(255, 255, 255, 255));")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(85, 87, 83, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.webcamFrame = QtWidgets.QLabel(self.centralwidget)
        self.webcamFrame.setGeometry(QtCore.QRect(220, 10, 591, 501))
        self.webcamFrame.setMouseTracking(False)
        self.webcamFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.webcamFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.webcamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.webcamFrame.setLineWidth(2)
        self.webcamFrame.setMidLineWidth(0)
        self.webcamFrame.setText("")
        self.webcamFrame.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.webcamFrame.setObjectName("webcamFrame")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(0, 10, 211, 371))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.startButton.setFont(font)
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.startButton.setAutoFillBackground(False)
        self.startButton.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(820, 10, 171, 491))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.stopButton.setFont(font)
        self.stopButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stopButton.setAutoFillBackground(False)
        self.stopButton.setStyleSheet("background-color: rgb(204, 0, 0);")
        self.stopButton.setObjectName("stopButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(220, 520, 591, 71))
        self.progressBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 20)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.logFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.logFileButton.setGeometry(QtCore.QRect(820, 520, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logFileButton.setFont(font)
        self.logFileButton.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.logFileButton.setObjectName("logFileButton")
        self.systemStatus = QtWidgets.QLabel(self.centralwidget)
        self.systemStatus.setGeometry(QtCore.QRect(10, 400, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.systemStatus.setFont(font)
        self.systemStatus.setObjectName("systemStatus")
        self.mainValveStatus = QtWidgets.QLabel(self.centralwidget)
        self.mainValveStatus.setGeometry(QtCore.QRect(10, 460, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.mainValveStatus.setFont(font)
        self.mainValveStatus.setObjectName("mainValveStatus")
        self.mainValveLED = QtWidgets.QLabel(self.centralwidget)
        self.mainValveLED.setGeometry(QtCore.QRect(170, 470, 31, 31))
        self.mainValveLED.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.mainValveLED.setText("")
        self.mainValveLED.setObjectName("mainValveLED")
        self.midValveStatus = QtWidgets.QLabel(self.centralwidget)
        self.midValveStatus.setGeometry(QtCore.QRect(10, 520, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.midValveStatus.setFont(font)
        self.midValveStatus.setObjectName("midValveStatus")
        self.midValveLED = QtWidgets.QLabel(self.centralwidget)
        self.midValveLED.setGeometry(QtCore.QRect(170, 530, 31, 31))
        self.midValveLED.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.midValveLED.setText("")
        self.midValveLED.setObjectName("midValveLED")
        self.calLCDNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.calLCDNumber.setGeometry(QtCore.QRect(620, 600, 191, 81))
        self.calLCDNumber.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.calLCDNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.calLCDNumber.setProperty("intValue", 0)
        self.calLCDNumber.setObjectName("calLCDNumber")
        self.calLabel = QtWidgets.QLabel(self.centralwidget)
        self.calLabel.setGeometry(QtCore.QRect(530, 600, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.calLabel.setFont(font)
        self.calLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.calLabel.setObjectName("calLabel")
        self.kpaLCDNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.kpaLCDNumber.setGeometry(QtCore.QRect(310, 600, 211, 81))
        self.kpaLCDNumber.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.kpaLCDNumber.setSmallDecimalPoint(False)
        self.kpaLCDNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.kpaLCDNumber.setProperty("value", 0.0)
        self.kpaLCDNumber.setProperty("intValue", 0)
        self.kpaLCDNumber.setObjectName("kpaLCDNumber")
        self.kpaLabel = QtWidgets.QLabel(self.centralwidget)
        self.kpaLabel.setGeometry(QtCore.QRect(220, 600, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.kpaLabel.setFont(font)
        self.kpaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kpaLabel.setObjectName("kpaLabel")
        self.systemLED = QtWidgets.QLabel(self.centralwidget)
        self.systemLED.setGeometry(QtCore.QRect(170, 410, 31, 31))
        self.systemLED.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.systemLED.setText("")
        self.systemLED.setObjectName("systemLED")
        self.captureAnDetectButton = QtWidgets.QPushButton(self.centralwidget)
        self.captureAnDetectButton.setGeometry(QtCore.QRect(10, 600, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.captureAnDetectButton.setFont(font)
        self.captureAnDetectButton.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.captureAnDetectButton.setObjectName("captureAnDetectButton")

        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(820, 600, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.resetButton.setObjectName("resetButton")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menuMain_layout = QtWidgets.QMenu(self.menubar)
        self.menuMain_layout.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.menuMain_layout.setObjectName("menuMain_layout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMain_layout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automated Calibration System GUI"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Estop"))
        self.logFileButton.setText(_translate("MainWindow", "Open log file"))
        self.systemStatus.setText(_translate("MainWindow", "System "))
        self.mainValveStatus.setText(_translate("MainWindow", "Main valve"))
        self.midValveStatus.setText(_translate("MainWindow", "Mid valve"))
        self.calLabel.setText(_translate("MainWindow", "Cal"))
        self.kpaLabel.setText(_translate("MainWindow", "Kpa"))
        self.captureAnDetectButton.setText(_translate("MainWindow", "Capture and detect"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.menuMain_layout.setTitle(_translate("MainWindow", "Main layout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
