# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIver4.0.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 606)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Documents/PlatformIO/Projects/kelco_test_001/beta.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.centralwidget.setStyleSheet("selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(85, 87, 83, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 931, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(110, 10, 181, 29))
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.calLabel = QtWidgets.QLabel(self.tab_3)
        self.calLabel.setGeometry(QtCore.QRect(480, 140, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.calLabel.setFont(font)
        self.calLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.calLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.calLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.calLabel.setLineWidth(2)
        self.calLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.calLabel.setObjectName("calLabel")
        self.kpaLabel = QtWidgets.QLabel(self.tab_3)
        self.kpaLabel.setGeometry(QtCore.QRect(480, 80, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.kpaLabel.setFont(font)
        self.kpaLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.kpaLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.kpaLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kpaLabel.setLineWidth(2)
        self.kpaLabel.setScaledContents(False)
        self.kpaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kpaLabel.setObjectName("kpaLabel")
        self.startButton = QtWidgets.QPushButton(self.tab_3)
        self.startButton.setGeometry(QtCore.QRect(50, 150, 201, 66))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.startButton.setFont(font)
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startButton.setAutoFillBackground(False)
        self.startButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.startButton.setDefault(True)
        self.startButton.setFlat(False)
        self.startButton.setObjectName("startButton")
        self.kpaLCDNumber = QtWidgets.QTextBrowser(self.tab_3)
        self.kpaLCDNumber.setGeometry(QtCore.QRect(720, 80, 171, 51))
        self.kpaLCDNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.kpaLCDNumber.setObjectName("kpaLCDNumber")
        self.calLCDNumber_2 = QtWidgets.QTextBrowser(self.tab_3)
        self.calLCDNumber_2.setGeometry(QtCore.QRect(720, 140, 171, 51))
        self.calLCDNumber_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.calLCDNumber_2.setObjectName("calLCDNumber_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(470, 20, 431, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(640, 30, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lowVoltageTestlabel = QtWidgets.QLabel(self.tab_3)
        self.lowVoltageTestlabel.setGeometry(QtCore.QRect(480, 230, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lowVoltageTestlabel.setFont(font)
        self.lowVoltageTestlabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lowVoltageTestlabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lowVoltageTestlabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lowVoltageTestlabel.setLineWidth(2)
        self.lowVoltageTestlabel.setScaledContents(False)
        self.lowVoltageTestlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lowVoltageTestlabel.setObjectName("lowVoltageTestlabel")
        self.lowVoltageTestResult = QtWidgets.QTextBrowser(self.tab_3)
        self.lowVoltageTestResult.setGeometry(QtCore.QRect(720, 230, 171, 51))
        self.lowVoltageTestResult.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lowVoltageTestResult.setObjectName("lowVoltageTestResult")
        self.lowVoltageTestlabel_2 = QtWidgets.QLabel(self.tab_3)
        self.lowVoltageTestlabel_2.setGeometry(QtCore.QRect(490, 300, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lowVoltageTestlabel_2.setFont(font)
        self.lowVoltageTestlabel_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lowVoltageTestlabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lowVoltageTestlabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lowVoltageTestlabel_2.setLineWidth(2)
        self.lowVoltageTestlabel_2.setScaledContents(False)
        self.lowVoltageTestlabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lowVoltageTestlabel_2.setObjectName("lowVoltageTestlabel_2")
        self.highVoltageTestResult = QtWidgets.QTextBrowser(self.tab_3)
        self.highVoltageTestResult.setGeometry(QtCore.QRect(720, 300, 171, 51))
        self.highVoltageTestResult.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.highVoltageTestResult.setObjectName("highVoltageTestResult")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_5.setGeometry(QtCore.QRect(20, 80, 261, 161))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(100, 90, 101, 21))
        self.label_5.setObjectName("label_5")
        self.textBrowser_5.raise_()
        self.textBrowser.raise_()
        self.label.raise_()
        self.comboBox.raise_()
        self.calLabel.raise_()
        self.kpaLabel.raise_()
        self.startButton.raise_()
        self.kpaLCDNumber.raise_()
        self.calLCDNumber_2.raise_()
        self.label_2.raise_()
        self.lowVoltageTestlabel.raise_()
        self.lowVoltageTestResult.raise_()
        self.lowVoltageTestlabel_2.raise_()
        self.highVoltageTestResult.raise_()
        self.label_5.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 903, 459))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.webcamFrame = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.webcamFrame.setText("")
        self.webcamFrame.setObjectName("webcamFrame")
        self.gridLayout_5.addWidget(self.webcamFrame, 0, 0, 1, 2)
        self.closeButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.closeButton.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.closeButton.setDefault(True)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout_5.addWidget(self.closeButton, 3, 1, 1, 1)
        self.viewButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.viewButton.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.viewButton.setDefault(True)
        self.viewButton.setObjectName("viewButton")
        self.gridLayout_5.addWidget(self.viewButton, 3, 0, 1, 1)
        self.Snap = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Snap.setObjectName("Snap")
        self.gridLayout_5.addWidget(self.Snap, 3, 2, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automated Calibration System GUI"))
        self.label.setText(_translate("MainWindow", "Model:"))
        self.calLabel.setText(_translate("MainWindow", "Cal"))
        self.kpaLabel.setText(_translate("MainWindow", "kPa"))
        self.startButton.setText(_translate("MainWindow", "Go"))
        self.kpaLCDNumber.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">--</span></p></body></html>"))
        self.calLCDNumber_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">--</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Result"))
        self.lowVoltageTestlabel.setText(_translate("MainWindow", "Low-voltage test"))
        self.lowVoltageTestResult.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">--</span></p></body></html>"))
        self.lowVoltageTestlabel_2.setText(_translate("MainWindow", "High-voltage test"))
        self.highVoltageTestResult.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">--</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Controller"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Controller"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.viewButton.setText(_translate("MainWindow", "View"))
        self.Snap.setText(_translate("MainWindow", "Snap"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Webcam"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle(QtWidgets.QStyleFactory.create('Cleanlooks'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
