import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, Qt
from PyQt5.QtGui import QImage, QPixmap, QFont

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Initialize webcam
        self.cap = cv2.VideoCapture(0)

        # Set up a timer to update the webcam frame
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_frame)
        self.timer.start(20)  # Update the frame every 20ms
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("beta.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget") 
        self.webcam_label = QtWidgets.QLabel(self.centralwidget)
        self.webcam_label.setGeometry(QtCore.QRect(0, 90, 321, 251))
        self.webcam_label.setMouseTracking(False)
        self.webcam_label.setFrameShape(QtWidgets.QFrame.Box)
        self.webcam_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.webcam_label.setLineWidth(3)
        self.webcam_label.setMidLineWidth(0)
        self.webcam_label.setText("")
        self.webcam_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.webcam_label.setObjectName("webcam_label")
        self.webcamFrameTitle = QtWidgets.QLabel(self.centralwidget)
        self.webcamFrameTitle.setGeometry(QtCore.QRect(0, 50, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.webcamFrameTitle.setFont(font)
        self.webcamFrameTitle.setAutoFillBackground(False)
        self.webcamFrameTitle.setStyleSheet("background-color: rgb(138, 226, 52);\n"
"")
        self.webcamFrameTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.webcamFrameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.webcamFrameTitle.setLineWidth(3)
        self.webcamFrameTitle.setScaledContents(True)
        self.webcamFrameTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.webcamFrameTitle.setObjectName("webcamFrameTitle")
        self.imageCaptured_label = QtWidgets.QLabel(self.centralwidget)
        self.imageCaptured_label.setGeometry(QtCore.QRect(320, 90, 311, 251))
        self.imageCaptured_label.setMouseTracking(False)
        self.imageCaptured_label.setFrameShape(QtWidgets.QFrame.Box)
        self.imageCaptured_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imageCaptured_label.setLineWidth(3)
        self.imageCaptured_label.setMidLineWidth(0)
        self.imageCaptured_label.setText("")
        self.imageCaptured_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.imageCaptured_label.setObjectName("imageCaptured_label")
        self.imageCapturedFrameTitle = QtWidgets.QLabel(self.centralwidget)
        self.imageCapturedFrameTitle.setGeometry(QtCore.QRect(320, 50, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.imageCapturedFrameTitle.setFont(font)
        self.imageCapturedFrameTitle.setAutoFillBackground(False)
        self.imageCapturedFrameTitle.setStyleSheet("background-color: rgb(138, 226, 52);\n"
"")
        self.imageCapturedFrameTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.imageCapturedFrameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageCapturedFrameTitle.setLineWidth(3)
        self.imageCapturedFrameTitle.setScaledContents(True)
        self.imageCapturedFrameTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.imageCapturedFrameTitle.setObjectName("imageCapturedFrameTitle")
        self.CroppedROI_label = QtWidgets.QLabel(self.centralwidget)
        self.CroppedROI_label.setGeometry(QtCore.QRect(0, 390, 321, 221))
        self.CroppedROI_label.setMouseTracking(False)
        self.CroppedROI_label.setFrameShape(QtWidgets.QFrame.Box)
        self.CroppedROI_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CroppedROI_label.setLineWidth(3)
        self.CroppedROI_label.setMidLineWidth(0)
        self.CroppedROI_label.setText("")
        self.CroppedROI_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.CroppedROI_label.setObjectName("CroppedROI_label")
        self.CroppedROITitle = QtWidgets.QLabel(self.centralwidget)
        self.CroppedROITitle.setGeometry(QtCore.QRect(0, 350, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CroppedROITitle.setFont(font)
        self.CroppedROITitle.setAutoFillBackground(False)
        self.CroppedROITitle.setStyleSheet("background-color: rgb(138, 226, 52);\n"
"")
        self.CroppedROITitle.setFrameShape(QtWidgets.QFrame.Box)
        self.CroppedROITitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CroppedROITitle.setLineWidth(3)
        self.CroppedROITitle.setScaledContents(True)
        self.CroppedROITitle.setAlignment(QtCore.Qt.AlignCenter)
        self.CroppedROITitle.setObjectName("CroppedROITitle")
        self.TextDetected_label = QtWidgets.QLabel(self.centralwidget)
        self.TextDetected_label.setGeometry(QtCore.QRect(320, 390, 311, 221))
        self.TextDetected_label.setMouseTracking(False)
        self.TextDetected_label.setFrameShape(QtWidgets.QFrame.Box)
        self.TextDetected_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TextDetected_label.setLineWidth(3)
        self.TextDetected_label.setMidLineWidth(0)
        self.TextDetected_label.setText("")
        self.TextDetected_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.TextDetected_label.setObjectName("TextDetected_label")
        self.TextDetectedTitle = QtWidgets.QLabel(self.centralwidget)
        self.TextDetectedTitle.setGeometry(QtCore.QRect(320, 350, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.TextDetectedTitle.setFont(font)
        self.TextDetectedTitle.setAutoFillBackground(False)
        self.TextDetectedTitle.setStyleSheet("background-color: rgb(138, 226, 52);\n"
"")
        self.TextDetectedTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.TextDetectedTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TextDetectedTitle.setLineWidth(3)
        self.TextDetectedTitle.setScaledContents(True)
        self.TextDetectedTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.TextDetectedTitle.setObjectName("TextDetectedTitle")
        self.MainTitle = QtWidgets.QLabel(self.centralwidget)
        self.MainTitle.setGeometry(QtCore.QRect(0, 0, 1161, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MainTitle.setFont(font)
        self.MainTitle.setStyleSheet("\n"
"background-color: rgb(187, 125, 231);")
        self.MainTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.MainTitle.setLineWidth(2)
        self.MainTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.MainTitle.setWordWrap(True)
        self.MainTitle.setObjectName("MainTitle")
        self.captureButton = QtWidgets.QPushButton(self.centralwidget)
        self.captureButton.setGeometry(QtCore.QRect(0, 620, 241, 201))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.captureButton.setFont(font)
        self.captureButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.captureButton.setAutoFillBackground(False)
        self.captureButton.setStyleSheet("background-color: rgb(114, 159, 207);\n"
"border-color: rgb(46, 52, 54);")
        icon = QtGui.QIcon.fromTheme("r")
        self.captureButton.setIcon(icon)
        self.captureButton.setObjectName("captureButton")
        self.captureButton.clicked.connect(self.capture)
        self.unlockPumpButton = QtWidgets.QPushButton(self.centralwidget)
        self.unlockPumpButton.setGeometry(QtCore.QRect(650, 100, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unlockPumpButton.setFont(font)
        self.unlockPumpButton.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.unlockPumpButton.setObjectName("unlockPumpButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(250, 620, 381, 201))
        self.textBrowser.setObjectName("textBrowser")
        self.calibrationModeButton = QtWidgets.QPushButton(self.centralwidget)
        self.calibrationModeButton.setGeometry(QtCore.QRect(650, 150, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.calibrationModeButton.setFont(font)
        self.calibrationModeButton.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.calibrationModeButton.setObjectName("calibrationModeButton")
        self.pressPButton = QtWidgets.QPushButton(self.centralwidget)
        self.pressPButton.setGeometry(QtCore.QRect(650, 200, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pressPButton.setFont(font)
        self.pressPButton.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.pressPButton.setObjectName("pressPButton")
        self.startCalibrateButton = QtWidgets.QPushButton(self.centralwidget)
        self.startCalibrateButton.setGeometry(QtCore.QRect(650, 350, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.startCalibrateButton.setFont(font)
        self.startCalibrateButton.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.startCalibrateButton.setObjectName("startCalibrateButton")
        self.manuallyCalibrateTitle = QtWidgets.QLabel(self.centralwidget)
        self.manuallyCalibrateTitle.setGeometry(QtCore.QRect(650, 50, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.manuallyCalibrateTitle.setFont(font)
        self.manuallyCalibrateTitle.setAutoFillBackground(False)
        self.manuallyCalibrateTitle.setStyleSheet("background-color: rgb(138, 226, 52);\n"
"")
        self.manuallyCalibrateTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.manuallyCalibrateTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manuallyCalibrateTitle.setLineWidth(3)
        self.manuallyCalibrateTitle.setScaledContents(True)
        self.manuallyCalibrateTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.manuallyCalibrateTitle.setObjectName("manuallyCalibrateTitle")
        self.rotatePaddlethenRButton = QtWidgets.QPushButton(self.centralwidget)
        self.rotatePaddlethenRButton.setGeometry(QtCore.QRect(650, 400, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rotatePaddlethenRButton.setFont(font)
        self.rotatePaddlethenRButton.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.rotatePaddlethenRButton.setObjectName("rotatePaddlethenRButton")
        self.rotateFlowtoNoFlowButton = QtWidgets.QPushButton(self.centralwidget)
        self.rotateFlowtoNoFlowButton.setGeometry(QtCore.QRect(650, 450, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rotateFlowtoNoFlowButton.setFont(font)
        self.rotateFlowtoNoFlowButton.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.rotateFlowtoNoFlowButton.setObjectName("rotateFlowtoNoFlowButton")
        self.rotateToFlowButton = QtWidgets.QPushButton(self.centralwidget)
        self.rotateToFlowButton.setGeometry(QtCore.QRect(650, 500, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rotateToFlowButton.setFont(font)
        self.rotateToFlowButton.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.rotateToFlowButton.setObjectName("rotateToFlowButton")
        self.actuatorControlTitle = QtWidgets.QLabel(self.centralwidget)
        self.actuatorControlTitle.setGeometry(QtCore.QRect(650, 580, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.actuatorControlTitle.setFont(font)
        self.actuatorControlTitle.setAutoFillBackground(False)
        self.actuatorControlTitle.setStyleSheet("background-color: rgb(138, 226, 52);\n"
"")
        self.actuatorControlTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.actuatorControlTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.actuatorControlTitle.setLineWidth(3)
        self.actuatorControlTitle.setScaledContents(True)
        self.actuatorControlTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.actuatorControlTitle.setObjectName("actuatorControlTitle")
        self.extendActuator1Button = QtWidgets.QPushButton(self.centralwidget)
        self.extendActuator1Button.setGeometry(QtCore.QRect(650, 630, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.extendActuator1Button.setFont(font)
        self.extendActuator1Button.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.extendActuator1Button.setObjectName("extendActuator1Button")
        self.retractActuator1Button = QtWidgets.QPushButton(self.centralwidget)
        self.retractActuator1Button.setGeometry(QtCore.QRect(710, 630, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.retractActuator1Button.setFont(font)
        self.retractActuator1Button.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.retractActuator1Button.setObjectName("retractActuator1Button")
        self.stopActuator1Button = QtWidgets.QPushButton(self.centralwidget)
        self.stopActuator1Button.setGeometry(QtCore.QRect(760, 630, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopActuator1Button.setFont(font)
        self.stopActuator1Button.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.stopActuator1Button.setObjectName("stopActuator1Button")
        self.extendActuator2Button = QtWidgets.QPushButton(self.centralwidget)
        self.extendActuator2Button.setGeometry(QtCore.QRect(650, 680, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.extendActuator2Button.setFont(font)
        self.extendActuator2Button.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.extendActuator2Button.setObjectName("extendActuator2Button")
        self.retractActuator2Button = QtWidgets.QPushButton(self.centralwidget)
        self.retractActuator2Button.setGeometry(QtCore.QRect(710, 680, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.retractActuator2Button.setFont(font)
        self.retractActuator2Button.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.retractActuator2Button.setObjectName("retractActuator2Button")
        self.stopActuator2Button = QtWidgets.QPushButton(self.centralwidget)
        self.stopActuator2Button.setGeometry(QtCore.QRect(760, 680, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopActuator2Button.setFont(font)
        self.stopActuator2Button.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.stopActuator2Button.setObjectName("stopActuator2Button")
        self.pressActuator1Button = QtWidgets.QPushButton(self.centralwidget)
        self.pressActuator1Button.setGeometry(QtCore.QRect(820, 630, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pressActuator1Button.setFont(font)
        self.pressActuator1Button.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.pressActuator1Button.setObjectName("pressActuator1Button")
        self.pressActuator2Button = QtWidgets.QPushButton(self.centralwidget)
        self.pressActuator2Button.setGeometry(QtCore.QRect(820, 680, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pressActuator2Button.setFont(font)
        self.pressActuator2Button.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.pressActuator2Button.setObjectName("pressActuator2Button")
        self.openAirValveButton = QtWidgets.QPushButton(self.centralwidget)
        self.openAirValveButton.setGeometry(QtCore.QRect(650, 250, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.openAirValveButton.setFont(font)
        self.openAirValveButton.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.openAirValveButton.setObjectName("openAirValveButton")
        self.closeAirValveButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeAirValveButton.setGeometry(QtCore.QRect(650, 300, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.closeAirValveButton.setFont(font)
        self.closeAirValveButton.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.closeAirValveButton.setObjectName("closeAirValveButton")
        self.extendActuator3Button = QtWidgets.QPushButton(self.centralwidget)
        self.extendActuator3Button.setGeometry(QtCore.QRect(650, 730, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.extendActuator3Button.setFont(font)
        self.extendActuator3Button.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.extendActuator3Button.setObjectName("extendActuator3Button")
        self.extendActuator4Button = QtWidgets.QPushButton(self.centralwidget)
        self.extendActuator4Button.setGeometry(QtCore.QRect(650, 780, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.extendActuator4Button.setFont(font)
        self.extendActuator4Button.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.extendActuator4Button.setObjectName("extendActuator4Button")
        self.retractActuator3Button = QtWidgets.QPushButton(self.centralwidget)
        self.retractActuator3Button.setGeometry(QtCore.QRect(710, 730, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.retractActuator3Button.setFont(font)
        self.retractActuator3Button.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.retractActuator3Button.setObjectName("retractActuator3Button")
        self.retractActuator4Button = QtWidgets.QPushButton(self.centralwidget)
        self.retractActuator4Button.setGeometry(QtCore.QRect(710, 780, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.retractActuator4Button.setFont(font)
        self.retractActuator4Button.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.retractActuator4Button.setObjectName("retractActuator4Button")
        self.stopActuator3Button = QtWidgets.QPushButton(self.centralwidget)
        self.stopActuator3Button.setGeometry(QtCore.QRect(760, 730, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopActuator3Button.setFont(font)
        self.stopActuator3Button.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.stopActuator3Button.setObjectName("stopActuator3Button")
        self.stopActuator4Button = QtWidgets.QPushButton(self.centralwidget)
        self.stopActuator4Button.setGeometry(QtCore.QRect(760, 780, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopActuator4Button.setFont(font)
        self.stopActuator4Button.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.stopActuator4Button.setObjectName("stopActuator4Button")
        self.pressActuator3Button = QtWidgets.QPushButton(self.centralwidget)
        self.pressActuator3Button.setGeometry(QtCore.QRect(820, 730, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pressActuator3Button.setFont(font)
        self.pressActuator3Button.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.pressActuator3Button.setObjectName("pressActuator3Button")
        self.pressActuator4Button = QtWidgets.QPushButton(self.centralwidget)
        self.pressActuator4Button.setGeometry(QtCore.QRect(820, 780, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pressActuator4Button.setFont(font)
        self.pressActuator4Button.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.pressActuator4Button.setObjectName("pressActuator4Button")
        self.automaticallyCalibratetitle = QtWidgets.QLabel(self.centralwidget)
        self.automaticallyCalibratetitle.setGeometry(QtCore.QRect(910, 50, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.automaticallyCalibratetitle.setFont(font)
        self.automaticallyCalibratetitle.setAutoFillBackground(False)
        self.automaticallyCalibratetitle.setStyleSheet("background-color: rgb(138, 226, 52);\n"
"")
        self.automaticallyCalibratetitle.setFrameShape(QtWidgets.QFrame.Box)
        self.automaticallyCalibratetitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.automaticallyCalibratetitle.setLineWidth(3)
        self.automaticallyCalibratetitle.setScaledContents(True)
        self.automaticallyCalibratetitle.setAlignment(QtCore.Qt.AlignCenter)
        self.automaticallyCalibratetitle.setObjectName("automaticallyCalibratetitle")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(910, 100, 251, 131))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"border-color: rgb(252, 233, 79);")
        self.startButton.setObjectName("startButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menuMain_layout = QtWidgets.QMenu(self.menubar)
        self.menuMain_layout.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.menuMain_layout.setObjectName("menuMain_layout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMain_layout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automated Calibration System GUI"))
        self.webcamFrameTitle.setText(_translate("MainWindow", "Webcam Frame"))
        self.imageCapturedFrameTitle.setText(_translate("MainWindow", "Image Captured Frame"))
        self.CroppedROITitle.setText(_translate("MainWindow", "Cropped ROI Frame"))
        self.TextDetectedTitle.setText(_translate("MainWindow", "Text Detected Frame"))
        self.MainTitle.setText(_translate("MainWindow", "Automated Calibration System"))
        self.captureButton.setText(_translate("MainWindow", "Capture and extract text"))
        self.unlockPumpButton.setText(_translate("MainWindow", "Unlock the pump controller"))
        self.calibrationModeButton.setText(_translate("MainWindow", "Calibration mode"))
        self.pressPButton.setText(_translate("MainWindow", "\"Pressing P\""))
        self.startCalibrateButton.setText(_translate("MainWindow", "Start calibrate"))
        self.manuallyCalibrateTitle.setText(_translate("MainWindow", "Manually calibrate"))
        self.rotatePaddlethenRButton.setText(_translate("MainWindow", "Rotate paddle and \"R\""))
        self.rotateFlowtoNoFlowButton.setText(_translate("MainWindow", "Roatate FLOW -> NO FLOW"))
        self.rotateToFlowButton.setText(_translate("MainWindow", "Roatate -> FLOW "))
        self.actuatorControlTitle.setText(_translate("MainWindow", "Actuators control"))
        self.extendActuator1Button.setText(_translate("MainWindow", "E1"))
        self.retractActuator1Button.setText(_translate("MainWindow", "R1"))
        self.stopActuator1Button.setText(_translate("MainWindow", "S1"))
        self.extendActuator2Button.setText(_translate("MainWindow", "E2"))
        self.retractActuator2Button.setText(_translate("MainWindow", "R2"))
        self.stopActuator2Button.setText(_translate("MainWindow", "S2"))
        self.pressActuator1Button.setText(_translate("MainWindow", "Press A1"))
        self.pressActuator2Button.setText(_translate("MainWindow", "Press A2"))
        self.openAirValveButton.setText(_translate("MainWindow", "Open air valve"))
        self.closeAirValveButton.setText(_translate("MainWindow", "Close air valve"))
        self.extendActuator3Button.setText(_translate("MainWindow", "E3"))
        self.extendActuator4Button.setText(_translate("MainWindow", "E4"))
        self.retractActuator3Button.setText(_translate("MainWindow", "R3"))
        self.retractActuator4Button.setText(_translate("MainWindow", "R4"))
        self.stopActuator3Button.setText(_translate("MainWindow", "S3"))
        self.stopActuator4Button.setText(_translate("MainWindow", "S4"))
        self.pressActuator3Button.setText(_translate("MainWindow", "Press A3"))
        self.pressActuator4Button.setText(_translate("MainWindow", "Press A4"))
        self.automaticallyCalibratetitle.setText(_translate("MainWindow", "Automatically calibrate"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.menuMain_layout.setTitle(_translate("MainWindow", "Main layout"))

    def update_frame(self):
        ret, frame = self.cap.read()
        if ret:
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            h, w, ch = rgb_frame.shape
            bytes_per_line = ch * w
            qt_image = QImage(rgb_frame.data, w, h, bytes_per_line, QImage.Format_RGB888)
            qt_pixmap = QPixmap.fromImage(qt_image)
            self.webcam_label.setPixmap(qt_pixmap)
            self.webcam_label.setAlignment(Qt.AlignCenter)
            self.webcam_label.setScaledContents(True)

    def capture(self):
        ret, frame = self.cap.read()
        if ret:
            cv2.imwrite("snapshot.jpg", frame)
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        #   img_with_text, extracted_text = self.ocr_processor.run_ocr("snapshot.jpg")
            h, w, ch = rgb_frame.shape
            bytes_per_line = ch * w
            qt_image = QImage(rgb_frame.data, w, h, bytes_per_line, QImage.Format_RGB888)
            qt_pixmap = QPixmap.fromImage(qt_image)
            self.imageCaptured_label.setPixmap(qt_pixmap)
            self.imageCaptured_label.setAlignment(Qt.AlignCenter)
            self.imageCaptured_label.setScaledContents(True)
            



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
